name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleRelease
      run: ls ${{github.workspace}}/app/build
      run: sudo apt install tree
      run: tree ${{github.workspace}}
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        name: test-apk
        path: ${{github.workspace}}/app/build/intermediates/apk/release/*.apk
